services:
  app:
    image: telegram/gymmybot
    restart: always
    ports:
      - 8080:8080

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?err}"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./src/main/resources/db/initDB.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports: [ "7777:8080" ]
    links: [ "postgres" ]

volumes:
  postgres:
    driver: local
